# Generated by Django 5.2.8 on 2025-12-01 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目分类',
                'verbose_name_plural': '题目分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='题目标题')),
                ('content', models.TextField(verbose_name='题目内容（支持HTML）')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题')], max_length=20, verbose_name='题目类型')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='难度等级')),
                ('score', models.PositiveIntegerField(default=5, verbose_name='分值')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='选项')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='题目解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.category', verbose_name='题目分类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question_type', 'difficulty'], name='exam_questi_questio_f33fb5_idx'), models.Index(fields=['category', 'is_active'], name='exam_questi_categor_221a69_idx')],
            },
        ),
    ]
