# Generated by Django 5.2.8 on 2025-12-01 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='考试名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='考试描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.PositiveIntegerField(verbose_name='考试时长（分钟）')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='总分')),
                ('pass_score', models.PositiveIntegerField(default=60, verbose_name='及格分数')),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='最大尝试次数')),
                ('show_answer', models.BooleanField(default=True, verbose_name='考试结束后显示答案')),
                ('show_score', models.BooleanField(default=True, verbose_name='考试结束后显示分数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('ongoing', '进行中'), ('finished', '已结束')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='试卷名称')),
                ('generate_type', models.CharField(choices=[('manual', '手动选题'), ('random', '随机组卷')], default='manual', max_length=20, verbose_name='生成方式')),
                ('random_rules', models.JSONField(blank=True, default=dict, verbose_name='随机组卷规则')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='exam.exam', verbose_name='所属考试')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='题目顺序')),
                ('score', models.PositiveIntegerField(verbose_name='分值')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='exam.paper', verbose_name='试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目',
                'ordering': ['order', 'id'],
                'unique_together': {('paper', 'question')},
            },
        ),
    ]
