# Generated by Django 5.2.8 on 2025-12-01 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_paper_paperquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=500, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('score', models.FloatField(default=0, verbose_name='得分')),
            ],
            options={
                'verbose_name': '答案记录',
                'verbose_name_plural': '答案记录',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('in_progress', '答题中'), ('submitted', '已提交'), ('timeout', '超时')], default='in_progress', max_length=20, verbose_name='状态')),
                ('total_score', models.FloatField(default=0, verbose_name='总分')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否及格')),
            ],
            options={
                'verbose_name': '考试答题记录',
                'verbose_name_plural': '考试答题记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='exam_questi_questio_f33fb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='exam_questi_categor_221a69_idx',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.exam', verbose_name='考试'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exam.paper', verbose_name='试卷'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='考生'),
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.examattempt', verbose_name='答题记录'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('exam', 'paper', 'user', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
