# Generated by Django 5.2.8 on 2025-12-03 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_answer_examattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('subjective', '主观题')], max_length=20, verbose_name='题目类型'),
        ),
        migrations.CreateModel(
            name='ExamActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('heartbeat', '心跳'), ('visibility_hidden', '页面隐藏（切屏/最小化）'), ('visibility_visible', '页面重新可见'), ('window_blur', '窗口失焦'), ('window_focus', '窗口获得焦点')], max_length=50, verbose_name='事件类型')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='事件详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='exam.examattempt', verbose_name='答题记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '考试行为日志',
                'verbose_name_plural': '考试行为日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
