# Generated by Django 5.2.8 on 2025-12-07 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_question_question_type_examactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='快速练习', max_length=200, verbose_name='练习标题')),
                ('question_type', models.CharField(blank=True, choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('subjective', '主观题')], max_length=20, null=True, verbose_name='题目类型')),
                ('difficulty', models.CharField(blank=True, choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], max_length=20, null=True, verbose_name='难度等级')),
                ('question_count', models.PositiveIntegerField(default=10, verbose_name='题目数量')),
                ('status', models.CharField(choices=[('in_progress', '练习中'), ('submitted', '已完成')], default='in_progress', max_length=20, verbose_name='状态')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='答对数量')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='题目总数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.category', verbose_name='题目分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习会话',
                'verbose_name_plural': '练习会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='题目顺序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='题目')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_questions', to='exam.practicesession', verbose_name='练习会话')),
            ],
            options={
                'verbose_name': '练习题目',
                'verbose_name_plural': '练习题目',
                'ordering': ['order', 'id'],
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, default='', max_length=500, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='题目')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_answers', to='exam.practicesession', verbose_name='练习会话')),
            ],
            options={
                'verbose_name': '练习答案',
                'verbose_name_plural': '练习答案',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
