# Generated by Django 5.2.8 on 2025-12-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_practicesession_practicequestion_practiceanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/%Y/%m/', verbose_name='题目图片（题干/选项合图）'),
        ),
    ]
