# Generated by Django 5.2.8 on 2025-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practicequestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='practicequestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='practicequestion',
            name='session',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='category',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='题目图片'),
        ),
        migrations.DeleteModel(
            name='PracticeAnswer',
        ),
        migrations.DeleteModel(
            name='PracticeQuestion',
        ),
        migrations.DeleteModel(
            name='PracticeSession',
        ),
    ]
