# Generated by Django 5.2.8 on 2025-12-07 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_add_answer_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='exam.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_questions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏题目',
                'verbose_name_plural': '收藏题目',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('exam', '考试'), ('practice', '练习')], default='exam', max_length=20, verbose_name='来源')),
                ('wrong_count', models.PositiveIntegerField(default=1, verbose_name='累计错误次数')),
                ('last_wrong_at', models.DateTimeField(auto_now=True, verbose_name='最后错误时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_users', to='exam.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题',
                'ordering': ['-last_wrong_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
