# Generated by Django 5.2.8 on 2025-12-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_favoritequestion_wrongquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examactivitylog',
            name='event_type',
            field=models.CharField(choices=[('heartbeat', '心跳'), ('visibility_hidden', '页面隐藏（切屏/最小化）'), ('visibility_visible', '页面重新可见'), ('window_blur', '窗口失焦'), ('window_focus', '窗口获得焦点'), ('force_submit', '强制提交'), ('other', '其他事件')], max_length=50, verbose_name='事件类型'),
        ),
    ]
